import Head from "next/head";
import { Header } from "../components/Header";
import Link from "next/link";

export default function Home() {
  const infos = [
    {
      text: "Our History",
      imageUrl: "launch-1.jpg",
    },
    {
      text: "Our Payload",
      imageUrl: "launch-3.jpg",
    },
  ];
  return (
    <div>
      <Head>
        <title>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div
          className={` h-screen bg-[url('/images/launch-1.jpg')]
 bg-origin-padding bg-top bg-no-repeat bg-cover text-white flex flex-col justify-center items-start p-20 gap-4`}
        >
          <h1 className="text-8xl tracking-widest font-bebas">our history</h1>
          <Link href="/history">
            <button className="text-xl font-bold uppercase text-white p-4 w-52 border-2 border-white transition-colors duration-500 ease-in-out hover:bg-white hover:text-black">
              Learn More
            </button>
          </Link>
        </div>
        <div
          className={` h-screen bg-[url('/images/rocket-1-medium.jpg')]
 bg-origin-padding bg-top bg-no-repeat bg-cover text-white flex flex-col justify-center items-start p-20 gap-4`}
        >
          <h1 className="text-8xl tracking-widest font-bebas">our payload</h1>
          <Link href="/payload">
            <button className="text-xl font-bold uppercase text-white p-4 w-52 border-2 border-white transition-colors duration-500 ease-in-out hover:bg-white hover:text-black">
              Learn More
            </button>
          </Link>
        </div>
      </main>
    </div>
  );
}